language: java

dist: xenial

env:
  global:
    - JRE8_HOME=/usr/lib/jvm/java-8-openjdk-amd64/jre

matrix:
  include:
    - os: linux
      jdk: oraclejdk11
      git:
        depth: false
    - os: linux
      jdk: openjdk8
    - os: osx
      before_install:
        - brew update
        - brew install ant

addons:
  apt:
    sources:
      - sourceline: 'deb https://dl.winehq.org/wine-builds/ubuntu/ xenial main'
        key_url: https://dl.winehq.org/wine-builds/winehq.key
    packages:
      - ant-optional
      - lib32ncurses5
      - lib32z1
      - winehq-stable

before_script:
  - ant -diagnostics

script:
  - ant -noinput -DignoreWineErrors=true
