name: build

on: [push]

jobs:
  build:
    runs-on: windows-latest
    strategy:
      matrix:
        java: [ '8', '9', '10', '11', '12' ]
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-java@v1
      with:
        java-version: ${{ matrix.java }}
    - run: ant -diagnostics
    - run: ant all
    - if: matrix.java == '11'
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      uses: sonarsource/sonarcloud-github-action@master
