name: Java CI

on: [push]

jobs:
  build:
    runs-on: windows-latest
    strategy:
      matrix:
        java: [ '8', '11' ]
        arch: [ 'x86', 'x64' ]
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-java@v1
      with:
        java-version: ${{ matrix.java }}
        architecture: ${{ matrix.arch }}
    - run: ant -diagnostics
    - run: ant all
